name: Build Multi-Arch Docker Image

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |-
            linux/amd64
            linux/arm64
        push: true
        tags: skewll/timetrex:latest
        cache-from: type=gha
        cache-to: type=gha
        
    - name: push README to Dockerhub
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
      with:
        destination_container_repo: skewll/timetrex
        provider: dockerhub
        short_description: 'TimeTrex Community Edition Docker Image'
        readme_file: 'README.md'